AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 637423486480

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: orgs_ameyermunoz
      AccountId: '637423486480'
      RootEmail: ameyermunoz+1@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
 
  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Production
      Accounts: 
        - !Ref ProductionAccount

  TestOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Test
      Accounts: 
        - !Ref TestAccount


  ProductionAccount:
      Type: OC::ORG::Account
      Properties:
        AccountName: Production Account
        RootEmail: ameyermunoz+3@gmail.com
        Alias: prod-account-983254

  TestAccount:
      Type: OC::ORG::Account
      Properties:
        AccountName: Test Account
        RootEmail: ameyermunoz+4@gmail.com
        Alias: test-account-983254


